constructor(string _uri, address _signerAddress, address[] _owners, address _stableCoinAddress, uint256 _numConfirmationsRequired) nonpayable
event AppartmentMinted(uint256 id, uint256 initialPricePerToken, uint256 initialYieldPerToken, uint256 totalSupply)
event ApprovalForAll(address indexed account, address indexed operator, bool approved)
event ConfirmCreateTokenRequest(address indexed owner, uint256 indexed txIndex)
event ExecuteCreateTokenRequest(address indexed owner, uint256 indexed txIndex)
event RevokeConfirmation(address indexed owner, uint256 indexed txIndex)
event SubmitCreateTokenRequest(address indexed owner, uint256 indexed requestIndex)
event TransferBatch(address indexed operator, address indexed from, address indexed to, uint256[] ids, uint256[] values)
event TransferSingle(address indexed operator, address indexed from, address indexed to, uint256 id, uint256 value)
event URI(string value, uint256 indexed id)
function balanceOf(address account, uint256 id) view returns (uint256)
function balanceOfBatch(address[] accounts, uint256[] ids) view returns (uint256[])
function getCreateTokenRequest(uint256 requestIndex) view returns (bool executed, uint256 numConfirmations)
function getInitialPricePerToken(uint256 id) view returns (uint256)
function getKYC(address addr) view returns (bool)
function getPayoutPerTokenAtSale(uint256 id) view returns (uint256)
function getRequestCount() view returns (uint256)
function getTotalSupply(uint256 id) view returns (uint256)
function isApprovedForAll(address account, address operator) view returns (bool)
function isConfirmed(uint256, address) view returns (bool)
function isKYCed(address) view returns (bool)
function isOwner(address) view returns (bool)
function mint(uint256 requestIndex)
function nConfirmations() view returns (uint256)
function owners(uint256) view returns (address)
function requests(uint256) view returns (address to, uint256 initialSupply, uint256 initialPricePerToken, uint256 yieldAtSale, bool executed, uint256 nConfirmations)
function revokeKYC(address addr)
function revokeSignature(uint256 requestIndex)
function safeBatchTransferFrom(address from, address to, uint256[] ids, uint256[] amounts, bytes data)
function safeTransferFrom(address from, address to, uint256 id, uint256 amount, bytes data)
function setApprovalForAll(address operator, bool approved)
function setKYC(tuple(uint8 v, bytes32 r, bytes32 s) signature)
function setKYCByOwner(address addr)
function signMintRequest(uint256 requestIndex)
function stableCoinAddress() view returns (address)
function submitMintRequest(address to, uint256 initialSupply, uint256 initialPricePerToken, uint256 yieldAtSale) returns (uint256)
function supportsInterface(bytes4 interfaceId) view returns (bool)
function uri(uint256) view returns (string)